apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-app
      color: blue
  template:
    metadata:
      labels:
        app: messaging-app
        color: blue
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:2.0 # Updated to version 2.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: messaging-app-config
        - secretRef:
            name: web-secret
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done;']
